---
title: "Introduction to Cognitive Psychology"
description: |
  What even is cognitive psychology?
author:
  - name: Janelle C.R. Mendoza 
    url: https://nerdwiththebeanie.netlify.app/
    affiliation: Brooklyn College
    affiliation_url: http://www.brooklyn.cuny.edu/web/home.php
date: 08-27-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

# What is Cognition?
Cognition according to Oxford Languages is defined as, "the mental action of process of acquiring knowledge and understanding through thought, experience, and the sense." However, if you were to ask me what the word means I'd likely go with a very unsatisfactory, *I don't know* because after 4 years under a bachelor's focused on animal behavior---I still don't know. From the basic senses to a more ambiguous term like "creativity," this field captures numerous aspects of what the brain is capable of.

I've always understood cognition from the perspective of building complexity throughout evolution, however it may be somewhat anthropocentric to insinuate that the closer an animal is to human the more complex their brain capacity is. We cannot thoroughly analyze what animal's "think" and there are many instances were our senses simply are outmatched by other species. Nonetheless, it is still interesting to look at the structure of the brain and how it may function like a tower of knowledge. Ernest Haeckel's theory of recapitulation states, "ontogeny recapitulates phylogeny" which to some extent is still applicable to cognition. In essence, he remarks that there is developmental parallels between animals and that through these parallels we can see the ancestry.

# My Interests
I am most interested in the ability to model cognition throughout evolution, particularly learning. Modeling can often times seem like reductive process, however it is in my belief that creating replicate models can prevent anthropomorphism. With my background in mathematical proofs and zoology, I'd like to additionally revisit old research to see if behavior models are logically sound. Behaviorism and cognition are usually approached as dichotomous, yet my ambition for my research is to build models that are reflective but not diminutive.

Various interest beyond learning include:

1. Language
2. Decision-Making
3. Problem-Solving
4. Social Dynamics

During our first class, professor Valian mentioned her interest in language and gender. As someone who speaks more than one language, I've always been interested in how our understanding of the world may shift through the language. For instance, I think the largest difference between Tagalog and English is that everyone's pronoun in Tagalog is "they." Perhaps this would only be applicable for my own experience, but I find myself not as attached to gender roles and I was raised to be more "masculine" than what is norm for Western society. It may be interesting to see how languages which have more gendered speech such as French may compare to languages like Tagalog which is more neutral.

Tied with simple models of learning, I think it is important to analyze decision-making and problem-solving where there may be some form of introspection prior to an action. I find decisions in social settings and how social pressure affects behavior to be very fascinating as there are so many unwritten rules of interactions. My first exposure to ethology was through problem-solving and how other animals solve puzzles. Despite I've generalized more to learning, I still enjoy learning more about other species.

Throughout my bachelors I was also on the women's rowing team, in that time I spent much of it defusing tense social situations and working in a high pressure environment. One of constant questions I had was the notion of competition within our team (for the higher tier boats) and how to balance that motivation to be a gripping force to do better without damaging relationships with teammates. I wondered if the unwarranted cruelty of waking up at 4 AM to go into frigid conditions and the discipline that came with the sport had a lasting net benefit or not. For all the amazing feats my teammates could achieve, the seedier underbelly of athlete's depression couldn't be remedied. Likewise for the closeness of our internal framework, it left minimal time to bond with people outside of the sport. Much of how I navigate social situations is reflexive of my time on that team, often in the form of a no-nonsense approach to my problems and a more *just deal with it* mentality. (I should put a caveat that this may not always be the best way to navigate a situation.) From aggression in women to the deep emotional bonds through the shared stress, the psychology of rowers (and by extension endurance athletes) to be tempting to research.

# Goals for This Course and This Blog
While my interest are more towards the foundation aspects of cognition where models can be built, I do think the more complex aspects of it that are harder to quantify would be worth looking into. I find that there is so much to explore within the subject that is is difficult to pinpoint a specific topic that I'd like to deepen my insight on. All of it seems rather fascinating to me and I look forward to synthesizing new information and ideas from what I learn.

Additionally, my goal for blogging is to compile my thoughts. Often times I find myself with a plethora of ideas and opinions, yet I am met with much difficult describing my thinking to others. Thus, I'd like to use this blog to improve my ability to explain my thinking. Not to mention, the act of writing in a colloquial fashion is enjoyable.